---
- name: copy role files
  copy:
    src: ./
    dest: /tmp/
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: create tiller service account
  k8s:
    src: /tmp/service-account.yml

- name: install helm cli
  become: yes
  become_user: root
  unarchive:
    src: https://storage.googleapis.com/kubernetes-helm/helm-{{ helm.version }}-linux-{{ helm.arch }}.tar.gz
    extra_opts:
      - "--strip-components=1"
      - "linux-{{ helm.arch }}/helm"
    dest: /usr/local/bin/
    mode: 0755
    remote_src: yes

- name: init helm
  shell: >
    helm init
    --tiller-image={{ helm.tiller_image }}
    --service-account tiller
    --upgrade
    --wait
