---
- name: template ark config
  template:
    src: ./ark-values.yml
    dest: /tmp/
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: install ark cli
  become: yes
  become_user: root
  unarchive:
    src: https://github.com/heptio/ark/releases/download/{{ ark.version }}/ark-{{ ark.version }}-linux-{{ ark.arch }}.tar.gz
    dest: /usr/local/bin/
    mode: 0755
    remote_src: yes

- name: install ark
  shell: >
    helm upgrade
    --install
    --namespace heptio-ark
    --values /tmp/ark-values.yml
    ark
    {{ ark.chart }}

- name: create schedule
  shell: >
    ark schedule get daily-backups || ark schedule create daily-backups --schedule "{{ backup.schedule }}" --ttl "{{ backup.ttl }}"
