---
- name: template cert secret file
  template:
    src: ./cert-secret.yml
    dest: /tmp/
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: create cert secret
  k8s:
    src: /tmp/cert-secret.yml

- name: template nginx config file
  template:
    src: ./nginx-values.yml
    dest: /tmp/
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

# lock to 0.20.0 nginx-ingress until UDP alternative exists
# https://github.com/kubernetes/ingress-nginx/pull/3197
- name: install nginx
  shell: >
    helm upgrade
    --install
    --namespace kube-system
    --values /tmp/nginx-values.yml
    --version 0.29.1
    nginx-ingress
    stable/nginx-ingress

- name: copy dns-updater chart
  copy:
    src: ../../../dns-updater
    dest: /tmp/
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: template dns-updater config file
  template:
    src: ./dns-updater-values.yml
    dest: /tmp/
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: install dns-updater
  shell: >
    helm upgrade
    --install
    --namespace kube-system
    --values /tmp/dns-updater-values.yml
    dns-updater
    /tmp/dns-updater
