---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-nginx-pvc
  labels:
    backup: "true"
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    backup: "true"
spec:
  selector:
    matchLabels:
      app: test-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: test-nginx
        backup: "true"
      annotations:
        backup.ark.heptio.com/backup-volumes: test-nginx
    spec:
      containers:
      - name: test-nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: test-nginx
      volumes:
      - name: test-nginx
        persistentVolumeClaim:
          claimName: test-nginx-pvc
---
kind: Service
apiVersion: v1
metadata:
  labels:
    backup: "true"
  name: test-nginx
spec:
  selector:
    app: test-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
# 1. Create test index page on volume:
#    - kubectl exec -it nginx-deployment-XXXXX -- /bin/sh -c 'echo "Hello World!" > /usr/share/nginx/html/index.html'
# 2. Connect to cluster VPN and curl service IP
# 3. Take a backup:
#    - ark backup create nginx-backup --selector app=nginx
