---
image:
  repository: jacobalberty/unifi
  tag: arm32v7-beta
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/tls-acme: "true"
  hosts:
    - unifi.{{ ingress.domain }}
  tls:
    - hosts:
      - unifi.{{ ingress.domain }}
      secretName: unifi-cert
controllerService:
  externalIPs:
    - {{ansible_default_ipv4.address}}
  port: 8080
stunService:
  externalIPs:
    - {{ansible_default_ipv4.address}}
  port: 3478
discoveryService:
  externalIPs:
    - {{ansible_default_ipv4.address}}
  port: 10001
persistence:
  enabled: true
  storageClass: gluster-heketi
  accessModes: ReadWriteOnce
  size: "10Gi"
podAnnotations:
  backup.ark.heptio.com/backup-volumes: unifi-data
