---
image:
  repository: jacobalberty/unifi
  tag: arm32v7-beta
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/tls-acme: "true"
  hosts:
    - unifi.{{ ingress.domain }}
  tls:
    - hosts:
      - unifi.{{ ingress.domain }}
      secretName: unifi-cert
controllerService:
  type: LoadBalancer
  loadBalancerIP: {{ ingress.nginxStaticIP }}
  port: 8080
  annotations:
    metallb.universe.tf/allow-shared-ip: ingress-shared
stunService:
  type: LoadBalancer
  loadBalancerIP: {{ ingress.nginxStaticIP }}
  port: 3478
  annotations:
    metallb.universe.tf/allow-shared-ip: ingress-shared
discoveryService:
  type: LoadBalancer
  loadBalancerIP: {{ ingress.nginxStaticIP }}
  port: 10001
  annotations:
    metallb.universe.tf/allow-shared-ip: ingress-shared
persistence:
  enabled: true
  storageClass: gluster-heketi
  accessModes: ReadWriteOnce
podAnnotations:
  backup.ark.heptio.com/backup-volumes: unifi-data
