---
image:
  repository: {{ cert_manager_image.split(":")[0] }}
  tag: "{{ cert_manager_image.split(":")[1] }}"
ingressShim:
  defaultIssuerName: letsencrypt-prod
  defaultIssuerKind: ClusterIssuer
  defaultACMEChallengeType: dns01
  defaultACMEDNS01ChallengeProvider: {{ letsencrypt_challenge_provider }}
