---
- name: reset worker
  become: yes
  become_user: root
  shell: kubeadm reset -f

- name: create config directory
  file:
    path: "{{ansible_env.HOME}}/.kube/"
    state: directory
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"
    mode: 0755

- name: copy kube config
  delegate_to: "{{ groups['master'][0] }}"
  synchronize:
    src: "{{ansible_env.HOME}}/.kube/config"
    dest: "{{ansible_env.HOME}}/.kube/config"

- register: token_cmd
  become: yes
  become_user: root
  delegate_to: "{{ groups['master'][0] }}"
  shell: >
    kubeadm
    token create
    --ttl 5m

- name: join cluster
  become: yes
  become_user: root
  shell: >
    kubeadm
    join
    --tls-bootstrap-token "{{ token_cmd.stdout }}"
    --discovery-file "{{ansible_env.HOME}}/.kube/config"
