---
- name: upgrade node
  become: yes
  become_user: root
  shell: >
    kubeadm upgrade
    node config
    --kubelet-version "$(kubelet --version | cut -d ' ' -f 2)"

- name: restart kubelet
  become: yes
  become_user: root
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet

- name: create config directory
  file:
    path: "{{ansible_env.HOME}}/.kube/"
    state: directory
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"
    mode: 0755

- name: copy kube config
  delegate_to: "{{ groups['master'][0] }}"
  synchronize:
    src: "{{ansible_env.HOME}}/.kube/config"
    dest: "{{ansible_env.HOME}}/.kube/config"
