# required by synchronize module
- name: install rsync
  apt:
    name: rsync
    state: latest

- name: download kubectl to tmp/
  synchronize:
    mode: pull
    src: /usr/local/bin/kubectl
    dest: "{{ lookup('env', 'PWD') }}/tmp/"
