---
configInline:
  peers:
  - peer-address: "{{ ansible_default_ipv4.gateway }}"
    peer-asn: 64512
    my-asn: 64512
  address-pools:
  - name: default
    protocol: bgp
    addresses:
    - "{{ ansible_default_ipv4.gateway }}/24"
