---
- hosts: workers[-1]
  any_errors_fatal: true
  roles:
    - k8s-module
    - glusterfs

- hosts: master
  any_errors_fatal: true
  roles:
    - k8s-module
    - helm
    - ark

- hosts: master
  any_errors_fatal: true
  roles:
    - metallb
    - ingress
    - dashboard
    - openvpn
    - unifi
