---
- hosts: workers[-1]
  any_errors_fatal: true
  roles:
    - k8s-module
    - glusterfs

- hosts: workers[0]
  any_errors_fatal: true
  roles:
    - k8s-module
    - helm
    - ark
    - metallb
    - ingress
    - dashboard
    - openvpn
    - unifi
    - port-forwarding
