---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: kube-system
spec:
  acme:
    server: "{{ letsencrypt.server }}"
    email: "{{ letsencrypt.email }}"
    privateKeySecretRef:
      name: letsencrypt-prod
    dns01:
      providers:
        - name: cf-dns
          cloudflare:
            email: "{{ cloudflare.email }}"
            apiKeySecretRef:
              name: dns-updater-secret
              key: api_token
