---
controller:
  image:
    # pinned to commit which includes prometheus client panic fix but
    # still includes UDP support...
    # check out github.com/ljfranklin/nginx-ingress
    # make build ARCH=arm && make container ARCH=arm
    repository: ljfranklin/nginx-ingress-controller-arm
    tag: 0.20.0-tcpudp
  service:
    type: LoadBalancer
    loadBalancerIP: {{ ingress.nginxStaticIP }}
    annotations:
      metallb.universe.tf/allow-shared-ip: ingress-shared
  extraArgs:
    default-ssl-certificate: kube-system/default-backend-cert-secret
defaultBackend:
  image:
    repository: k8s.gcr.io/defaultbackend-arm
