---
- name: copy role files
  copy:
    src: ./
    dest: /tmp/
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: create tiller service account
  k8s:
    src: /tmp/service-account.yml

- name: install helm cli
  become: yes
  become_user: root
  unarchive:
    src: https://storage.googleapis.com/kubernetes-helm/helm-v2.12.0-linux-arm.tar.gz
    extra_opts:
      - "--strip-components=1"
      - "linux-arm/helm"
    dest: /usr/local/bin/
    mode: 0755
    remote_src: yes

- name: init helm
  # no official tiller image for arm yet
  # https://github.com/helm/helm/issues/3269
  # manually built from https://github.com/ljfranklin/helm-arm
  shell: >
    helm init
    --tiller-image=ljfranklin/helm-arm:2.12.0
    --service-account tiller
    --upgrade
    --wait
